name: Autocomment

on: pull_request

jobs:
  comment:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Autocomment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Thanks a lot for adding to this list 💖 Trully appreciate it!"
          check_for_duplicate_msg: false
